"""Add example_sentence_ru to words

Revision ID: 0b885dcfc8f0
Revises: 94e93521e2e7
Create Date: 2026-01-28 14:11:33.951561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b885dcfc8f0'
down_revision: Union[str, None] = '94e93521e2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('example_sentence_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'example_sentence_ru')
    # ### end Alembic commands ###
